import { Barlow_Condensed } from 'next/font/google'
import './globals.css'

const barlow = Barlow_Condensed({ subsets: ['latin'], weight:['100' , '200' , '300' , '400' , '500' , '600' , '700' , '800' , '900'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${barlow.className} bg-background max-w-screen h-screen  text-white -z-20`}>
        <div className="max-w-screen h-screen -z-20 justify-center p-6 flex">
        {children}
        </div>
        </body>
    </html>
  )
}
